export const responses =  [
  "Yes, absolutely.",
  "The signs point to no.",
  "It's unclear, ask again later.",
  "Without a doubt.",
  "My sources say no.",
  "Possibly… if you believe.",
  "The universe says maybe.",
  "Definitely not today.",
  "Yes, but tread carefully.",
  "You already know the answer.",
  "The stars are not aligned.",
  "Trust your instincts.",
  "A surprise awaits you.",
  "Not in this lifetime.",
  "The answer is hidden.",
  "Seek advice from a friend.",
  "Change is coming.",
  "Patience will reward you.",
  "The outcome is uncertain.",
  "You must take a leap of faith.",
  "Now is not the time.",
  "Good fortune is near.",
  "Beware of distractions.",
  "Your path will be revealed.",
  "Ask with a clear heart.",
  "The answer lies within.",
  "Proceed with caution.",
  "Let go and see what happens.",
  "You will find clarity soon.",
  "The odds are in your favor.",
  "It's better not to know.",
  "Success is certain.",
  "All will go well.",
  "Your wish will be granted.",
  "The outcome is favorable.",
  "You are on the right path.",
  "Expect a positive result.",
  "Joy is ahead.",
  "Victory is yours.",
  "The universe supports you.",
  "Your hopes will be fulfilled.",
  "A bright future awaits.",
  "Luck is on your side.",
  "You will find what you seek.",
  "Dreams will come true.",
  "Your efforts will be rewarded.",
  "Happiness is within reach.",
  "The answer is yes in spirit.",
  "Everything aligns for you.",
  "You will achieve your goal."
];